export const mentors = [
  { id: 1, name: "Ali Hassan", degree: "BS Computer Science", location: "Pakistan", university: "NUST, Islamabad", role: "Senior Software Engineer", expertise: ["React", "Node.js", "AWS"] },
  { id: 2, name: "Fatima Tariq", degree: "MPhil Data Science", location: "UK", university: "University of Oxford", role: "Data Scientist", expertise: ["Python", "Machine Learning", "SQL"] },
  { id: 3, name: "Usman Ali", degree: "BS Software Engineering", location: "Pakistan", university: "FAST NUCES", role: "Backend Developer", expertise: ["Go", "Microservices", "Docker"] },
  { id: 4, name: "Ayesha Khan", degree: "PhD Artificial Intelligence", location: "USA", university: "Stanford University", role: "AI Researcher", expertise: ["Deep Learning", "NLP", "PyTorch"] },
  { id: 5, name: "Bilal Ahmed", degree: "BS Computer Science", location: "Pakistan", university: "LUMS", role: "Full Stack Developer", expertise: ["Next.js", "TypeScript", "Prisma"] },
  { id: 6, name: "Zainab Raza", degree: "MPhil Software Engineering", location: "Australia", university: "University of Melbourne", role: "Cloud Architect", expertise: ["AWS", "Kubernetes", "Terraform"] },
  { id: 7, name: "Hassan Mehmood", degree: "BS Information Technology", location: "Saudia Arabia", university: "King Abdullah University", role: "Security Analyst", expertise: ["Cybersecurity", "Pen Testing"] },
  { id: 8, name: "Maryam Shafiq", degree: "BS Computer Science", location: "Pakistan", university: "PUCIT", role: "Mobile Developer", expertise: ["Flutter", "Dart", "Firebase"] },
  { id: 9, name: "Omar Farooq", degree: "BS Computer Engineering", location: "Pakistan", university: "UET Lahore", role: "Embedded Systems Engineer", expertise: ["C++", "IoT", "RTOS"] },
  { id: 10, name: "Saad Malik", degree: "MPhil Computer Science", location: "UK", university: "Imperial College London", role: "Tech Lead", expertise: ["System Design", "Java", "Spring Boot"] },
  { id: 11, name: "Hamza Iqbal", degree: "BS Software Engineering", location: "Pakistan", university: "COMSATS", role: "Frontend Developer", expertise: ["Vue.js", "Tailwind CSS", "JavaScript"] },
  { id: 12, name: "Khadija Bibi", degree: "BS Computer Science", location: "Pakistan", university: "Bahria University", role: "QA Engineer", expertise: ["Selenium", "Cypress", "Automation"] },
  { id: 13, name: "Abdullah Sheikh", degree: "PhD Computer Vision", location: "USA", university: "MIT", role: "Principal Engineer", expertise: ["Computer Vision", "OpenCV", "C++"] },
  { id: 14, name: "Amna Nawaz", degree: "BS Computer Science", location: "Australia", university: "University of Sydney", role: "Data Analyst", expertise: ["Tableau", "PowerBI", "SQL"] },
  { id: 15, name: "Ibrahim Qureshi", degree: "BS Information Technology", location: "Pakistan", university: "Arid Agriculture University", role: "DevOps Engineer", expertise: ["Jenkins", "CI/CD", "Linux"] },
  { id: 16, name: "Sana Javed", degree: "MPhil Artificial Intelligence", location: "Pakistan", university: "NUST, Islamabad", role: "Machine Learning Engineer", expertise: ["TensorFlow", "Python", "Data Mining"] },
  { id: 17, name: "Tariq Jamil", degree: "BS Computer Science", location: "Saudia Arabia", university: "King Saud University", role: "Backend Developer", expertise: ["PHP", "Laravel", "MySQL"] },
  { id: 18, name: "Sara Ahmed", degree: "BS Software Engineering", location: "Pakistan", university: "FAST NUCES", role: "UI/UX Designer", expertise: ["Figma", "Prototyping", "User Research"] },
  { id: 19, name: "Raza Ali", degree: "BS Computer Science", location: "UK", university: "University of Manchester", role: "Blockchain Developer", expertise: ["Solidity", "Web3.js", "Ethereum"] },
  { id: 20, name: "Zohaib Hassan", degree: "MPhil Data Science", location: "Pakistan", university: "LUMS", role: "Data Engineer", expertise: ["Apache Spark", "Hadoop", "Scala"] },
  { id: 21, name: "Hina Rabbani", degree: "BS Information Systems", location: "USA", university: "University of California, Berkeley", role: "Product Manager", expertise: ["Agile", "Scrum", "Product Strategy"] },
  { id: 22, name: "Fahad Mustafa", degree: "BS Computer Science", location: "Pakistan", university: "GIKI", role: "Game Developer", expertise: ["Unity", "C#", "3D Modeling"] },
  { id: 23, name: "Nida Yasir", degree: "BS Software Engineering", location: "Pakistan", university: "UET Taxila", role: "Frontend Developer", expertise: ["React", "Redux", "CSS"] },
  { id: 24, name: "Kamran Akmal", degree: "PhD Machine Learning", location: "Australia", university: "UNSW Sydney", role: "Research Scientist", expertise: ["Reinforcement Learning", "Python"] },
  { id: 25, name: "Muneeb Butt", degree: "BS Computer Science", location: "Pakistan", university: "NUST, Islamabad", role: "Full Stack Developer", expertise: ["MERN Stack", "GraphQL"] },
  { id: 26, name: "Aiman Khan", degree: "MPhil Software Engineering", location: "UK", university: "University College London", role: "Software Architect", expertise: ["Microservices", "Cloud Native"] },
  { id: 27, name: "Sheheryar Munawar", degree: "BS Computer Engineering", location: "Pakistan", university: "UET Lahore", role: "Hardware Engineer", expertise: ["FPGA", "Verilog", "VHDL"] },
  { id: 28, name: "Mahira Khan", degree: "BS Computer Science", location: "USA", university: "Georgia Tech", role: "Data Scientist", expertise: ["R", "Statistical Modeling", "Python"] },
  { id: 29, name: "Fawad Khan", degree: "BS Information Technology", location: "Pakistan", university: "PUCIT", role: "Cloud Engineer", expertise: ["Azure", "Kubernetes"] },
  { id: 30, name: "Sajal Aly", degree: "MPhil Computer Science", location: "Saudia Arabia", university: "King Fahd University", role: "Backend Engineer", expertise: ["Node.js", "Express", "MongoDB"] },
  { id: 31, name: "Ahad Raza", degree: "BS Software Engineering", location: "Pakistan", university: "FAST NUCES", role: "Mobile Developer", expertise: ["React Native", "iOS", "Android"] },
  { id: 32, name: "Iqra Aziz", degree: "BS Computer Science", location: "Pakistan", university: "COMSATS", role: "QA Automation Engineer", expertise: ["Playwright", "Jest"] },
  { id: 33, name: "Yasir Hussain", degree: "PhD Cybersecurity", location: "UK", university: "University of Edinburgh", role: "Security Researcher", expertise: ["Cryptography", "Network Security"] },
  { id: 34, name: "Maya Ali", degree: "BS Computer Science", location: "Australia", university: "Monash University", role: "Frontend Developer", expertise: ["Angular", "TypeScript"] },
  { id: 35, name: "Hamza Ali", degree: "BS Software Engineering", location: "Pakistan", university: "LUMS", role: "Full Stack Developer", expertise: ["Django", "React", "PostgreSQL"] },
  { id: 36, name: "Hania Aamir", degree: "MPhil Data Science", location: "Pakistan", university: "NUST, Islamabad", role: "Data Analyst", expertise: ["SQL", "Excel", "Data Visualization"] },
  { id: 37, name: "Farhan Saeed", degree: "BS Information Technology", location: "USA", university: "University of Washington", role: "DevOps Engineer", expertise: ["GitLab CI", "Ansible", "Docker"] },
  { id: 38, name: "Urwa Hocane", degree: "BS Computer Science", location: "Pakistan", university: "Bahria University", role: "UI/UX Designer", expertise: ["Adobe XD", "Sketch"] },
  { id: 39, name: "Mawra Hocane", degree: "BS Software Engineering", location: "Pakistan", university: "UET Lahore", role: "Backend Developer", expertise: ["Ruby on Rails", "Redis"] },
  { id: 40, name: "Ali Zafar", degree: "MPhil Computer Science", location: "UK", university: "King's College London", role: "Software Engineer", expertise: ["C++", "System Programming"] },
  { id: 41, name: "Atif Aslam", degree: "BS Computer Engineering", location: "Saudia Arabia", university: "King Abdulaziz University", role: "Network Engineer", expertise: ["Cisco", "Routing", "Switching"] },
  { id: 42, name: "Mehwish Hayat", degree: "BS Computer Science", location: "Pakistan", university: "PUCIT", role: "Frontend Developer", expertise: ["React", "Next.js"] },
  { id: 43, name: "Humayun Saeed", degree: "PhD Artificial Intelligence", location: "Australia", university: "University of Queensland", role: "AI Scientist", expertise: ["NLP", "Generative AI"] },
  { id: 44, name: "Ayesha Omar", degree: "BS Information Systems", location: "Pakistan", university: "FAST NUCES", role: "Business Analyst", expertise: ["Requirements Gathering", "UML"] },
  { id: 45, name: "Feroze Khan", degree: "BS Software Engineering", location: "USA", university: "University of Southern California", role: "Game Developer", expertise: ["Unreal Engine", "C++"] },
  { id: 46, name: "Saba Qamar", degree: "MPhil Software Engineering", location: "Pakistan", university: "LUMS", role: "Project Manager", expertise: ["Jira", "Agile", "Scrum"] },
  { id: 47, name: "Ahsan Khan", degree: "BS Computer Science", location: "Pakistan", university: "GIKI", role: "Full Stack Developer", expertise: ["Vue.js", "Node.js"] },
  { id: 48, name: "Neelam Muneer", degree: "BS Information Technology", location: "UK", university: "University of Warwick", role: "Database Administrator", expertise: ["Oracle", "SQL Server"] },
  { id: 49, name: "Imran Abbas", degree: "BS Computer Science", location: "Pakistan", university: "COMSATS", role: "Mobile Developer", expertise: ["Swift", "Objective-C"] },
  { id: 50, name: "Ayeza Khan", degree: "MPhil Data Science", location: "Saudia Arabia", university: "King Saud University", role: "Data Engineer", expertise: ["Kafka", "Spark"] },
  { id: 51, name: "Danish Taimoor", degree: "BS Software Engineering", location: "Pakistan", university: "UET Taxila", role: "Backend Developer", expertise: ["Java", "Spring"] },
  { id: 52, name: "Sarah Khan", degree: "BS Computer Science", location: "Australia", university: "University of Adelaide", role: "Frontend Developer", expertise: ["Svelte", "Tailwind"] },
  { id: 53, name: "Agha Ali", degree: "PhD Computer Vision", location: "USA", university: "Carnegie Mellon University", role: "Research Scientist", expertise: ["Computer Vision", "PyTorch"] },
  { id: 54, name: "Minal Khan", degree: "BS Information Technology", location: "Pakistan", university: "NUST, Islamabad", role: "Cloud Architect", expertise: ["AWS", "GCP"] },
  { id: 55, name: "Zahid Ahmed", degree: "BS Computer Science", location: "Pakistan", university: "FAST NUCES", role: "Software Engineer", expertise: ["Python", "Django"] },
  { id: 56, name: "Yumna Zaidi", degree: "MPhil Artificial Intelligence", location: "UK", university: "University of Bristol", role: "Machine Learning Engineer", expertise: ["Scikit-Learn", "Pandas"] },
  { id: 57, name: "Wahaj Ali", degree: "BS Software Engineering", location: "Pakistan", university: "LUMS", role: "UI/UX Designer", expertise: ["Figma", "CSS"] },
  { id: 58, name: "Kinza Hashmi", degree: "BS Computer Science", location: "Saudia Arabia", university: "King Abdullah University", role: "Full Stack Developer", expertise: ["React", "Ruby on Rails"] }
];
